image: db-ris-docker-release-local.bahnhub.tech.rz.db.de/base/alpine3.16:latest

stages:
  - pre-commit
  - prepare-ci
  - exec-ci

variables:
  AWS_STS_REGIONAL_ENDPOINTS: "regional"
  TERRAGRUNT_DOCKER_IMAGE: httpd:2.4.56-alpine
  TERRAGRUNT_PARALLELISM: 5
  CI_JOBS_DEPTH: 5
  TG_RUN_ALL_DESTROY_DEPTH_MIN: 2
  TG_RUN_ALL_DESTROY_DEPTH_MAX: 3

.tags:
  tags: [ci, mgln, privilege]

.generate:ci:jobs:
  stage: prepare-ci
  variables:
  script: ./ci/scripts/generate_ci_jobs.sh > child-gitlab-ci.yaml
  artifacts:
    paths:
      - child-gitlab-ci.yaml
  extends: .tags

check:pre-commit:
  stage: pre-commit
  image:
    name: httpd:2.4.56-alpine
    entrypoint:
      - ""
  script:
    - pre-commit run -a
  extends: .tags
